apiVersion: v1
kind: Service
metadata:
  name: rustyroad-http-service
  namespace: rustyroad
spec:
  selector:
      app: rustyroad
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rustyroad-tcp-service
  namespace: rustyroad
spec:
  type: NodePort
  selector:
    app: rustyroad
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080