name: Deploy to Cluster
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          # list of Docker images to use as base name for tags
          images: |
            ferdoran/rustyroad
          # add git short SHA as Docker tag
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - uses: actions/checkout@v2
      - uses: azure/setup-kubectl@v2.0
        id: install
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}
          cluster-type: generic
        id: setcontext
      - uses: azure/k8s-deploy@v1.5
        with:
          manifests: |
            _devops/manifests/deployment.yaml
            _devops/manifests/service.yaml
          namespace: ${{ secrets.CLUSTER_NAMESPACE }}
          images: "ferdoran/rustyroad:${{ steps.docker_meta.outputs.labels }}"
          kubectl-version: "latest"
